# Generated by Django 4.1.1 on 2023-03-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('reporter_name', models.CharField(max_length=100)),
                ('report_description', models.TextField()),
            ],
        ),
    ]
