# Generated by Django 4.1.1 on 2023-03-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='App.reportedphonenumber')),
            ],
        ),
    ]
