# Generated by Django 4.1.1 on 2023-03-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedphonenumber',
            name='report_description',
        ),
        migrations.RemoveField(
            model_name='reportedphonenumber',
            name='reporter_name',
        ),
    ]
