# Generated by Django 4.1.1 on 2023-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_reportedphonenumber_report_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedphonenumber',
            name='reported_phone_number_count',
            field=models.IntegerField(default=0),
        ),
    ]
